kind = "mobile"
previewPath = "/thanksgiving-mobile/"
title = "Headout Blog Mobile"
version = "1.0.0"
id = "artifacts/thanksgiving-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/thanksgiving-mobile/" ]
localPort = 23396

[services.development]
run = "pnpm --filter @workspace/thanksgiving-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/thanksgiving-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/thanksgiving-mobile", "run", "serve" ]

[services.env]
PORT = "23396"
BASE_PATH = "/thanksgiving-mobile/"
