import type { ContentBundle } from "./types.js";

/**
 * SQL export emits a portable, self-consistent set of `INSERT` statements for
 * the content tables, wrapped in a transaction and using `ON CONFLICT DO
 * NOTHING` so it can be replayed into a fresh Postgres database. Row ids are
 * deterministic UUIDs derived from natural keys, so foreign-key references line
 * up within the dump and re-running it is idempotent.
 *
 * SQL is an export/backup artifact only — there is no SQL parser. To restore
 * content into THIS application use the JSON backup + restore path, which upserts
 * by natural key and is transactional and non-destructive.
 */

/** Deterministic, dependency-free UUID derived from a seed string. */
export function pseudoUuid(seed: string): string {
  // xmur3 seed -> sfc32 PRNG -> 16 bytes, formatted as a v4-shaped UUID.
  let h = 1779033703 ^ seed.length;
  for (let i = 0; i < seed.length; i++) {
    h = Math.imul(h ^ seed.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  const next = () => {
    h = Math.imul(h ^ (h >>> 16), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    h ^= h >>> 16;
    return h >>> 0;
  };
  const bytes: number[] = [];
  while (bytes.length < 16) {
    const r = next();
    bytes.push(r & 0xff, (r >>> 8) & 0xff, (r >>> 16) & 0xff, (r >>> 24) & 0xff);
  }
  bytes.length = 16;
  bytes[6] = (bytes[6]! & 0x0f) | 0x40;
  bytes[8] = (bytes[8]! & 0x3f) | 0x80;
  const hex = bytes.map((b) => b.toString(16).padStart(2, "0"));
  return [
    hex.slice(0, 4).join(""),
    hex.slice(4, 6).join(""),
    hex.slice(6, 8).join(""),
    hex.slice(8, 10).join(""),
    hex.slice(10, 16).join(""),
  ].join("-");
}

function lit(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "object") {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insert(
  table: string,
  columns: string[],
  values: unknown[],
  conflict: string,
): string {
  return (
    `INSERT INTO ${table} (${columns.join(", ")})\n` +
    `  VALUES (${values.map(lit).join(", ")})\n` +
    `  ON CONFLICT ${conflict} DO NOTHING;`
  );
}

export function serializeSql(bundle: ContentBundle): string {
  const out: string[] = [];
  out.push("-- Content export (PostgreSQL). Generated by @workspace/content-io.");
  out.push(`-- exportedAt: ${bundle.exportedAt}`);
  out.push("BEGIN;");
  out.push("");

  const authorId = (slug: string) => pseudoUuid(`author:${slug}`);
  const categoryId = (slug: string) => pseudoUuid(`category:${slug}`);
  const tagId = (slug: string) => pseudoUuid(`tag:${slug}`);
  const pageId = (canonicalUrl: string) => pseudoUuid(`page:${canonicalUrl}`);

  out.push("-- authors");
  for (const a of bundle.authors) {
    out.push(
      insert(
        "authors",
        ["id", "name", "slug", "bio", "avatar_url", "role", "email", "social"],
        [authorId(a.slug), a.name, a.slug, a.bio ?? null, a.avatarUrl ?? null, a.role ?? null, a.email ?? null, a.social ?? null],
        "(slug)",
      ),
    );
  }

  out.push("", "-- categories");
  for (const c of bundle.categories) {
    out.push(
      insert(
        "categories",
        ["id", "name", "slug", "description"],
        [categoryId(c.slug), c.name, c.slug, c.description ?? null],
        "(slug)",
      ),
    );
  }
  for (const c of bundle.categories) {
    if (c.parentSlug) {
      out.push(
        `UPDATE categories SET parent_id = ${lit(categoryId(c.parentSlug))} WHERE slug = ${lit(c.slug)};`,
      );
    }
  }

  out.push("", "-- tags");
  for (const t of bundle.tags) {
    out.push(
      insert(
        "tags",
        ["id", "name", "slug", "description"],
        [tagId(t.slug), t.name, t.slug, t.description ?? null],
        "(slug)",
      ),
    );
  }

  out.push("", "-- pages + children");
  for (const p of bundle.posts) {
    const pid = pageId(p.canonicalUrl);
    out.push(
      insert(
        "pages",
        [
          "id", "slug", "title", "subtitle", "excerpt", "page_type", "status",
          "language", "original_url", "canonical_url", "pathname", "parent_path",
          "author_id", "primary_category_id", "featured_image_url",
          "featured_image_alt", "cleaned_html", "rich_text", "component_tree",
          "reading_time_minutes", "word_count", "published_at",
        ],
        [
          pid, p.slug, p.title, p.subtitle ?? null, p.excerpt ?? null, "post",
          p.status === "published" ? "published" : "draft", p.language,
          p.originalUrl ?? p.canonicalUrl, p.canonicalUrl, p.pathname,
          p.parentPath ?? null,
          p.authorSlug ? authorId(p.authorSlug) : null,
          p.primaryCategorySlug ? categoryId(p.primaryCategorySlug) : null,
          p.featuredImageUrl ?? null, p.featuredImageAlt ?? null,
          p.contentHtml ?? null, p.richText ?? null, p.componentTree ?? null,
          p.readingTimeMinutes ?? null, p.wordCount ?? null, p.publishedAt ?? null,
        ],
        "(canonical_url)",
      ),
    );
    for (const slug of p.categorySlugs) {
      out.push(
        insert(
          "page_categories",
          ["page_id", "category_id"],
          [pid, categoryId(slug)],
          "(page_id, category_id)",
        ),
      );
    }
    for (const slug of p.tagSlugs) {
      out.push(
        insert(
          "page_tags",
          ["page_id", "tag_id"],
          [pid, tagId(slug)],
          "(page_id, tag_id)",
        ),
      );
    }
    if (p.seo) {
      out.push(
        insert(
          "seo",
          [
            "id", "page_id", "meta_title", "meta_description", "canonical_url",
            "robots", "focus_keyword", "og_title", "og_description", "og_image",
            "og_type", "twitter_card", "twitter_title", "twitter_description",
            "twitter_image",
          ],
          [
            pseudoUuid(`seo:${p.canonicalUrl}`), pid, p.seo.metaTitle ?? null,
            p.seo.metaDescription ?? null, p.seo.canonicalUrl ?? null,
            p.seo.robots ?? null, p.seo.focusKeyword ?? null, p.seo.ogTitle ?? null,
            p.seo.ogDescription ?? null, p.seo.ogImage ?? null, p.seo.ogType ?? null,
            p.seo.twitterCard ?? null, p.seo.twitterTitle ?? null,
            p.seo.twitterDescription ?? null, p.seo.twitterImage ?? null,
          ],
          "(page_id)",
        ),
      );
    }
    for (const img of p.images) {
      out.push(
        insert(
          "images",
          [
            "id", "page_id", "original_url", "url", "alt", "title", "caption",
            "credit", "width", "height", "mime_type", "file_size", "role",
            "position",
          ],
          [
            pseudoUuid(`image:${p.canonicalUrl}:${img.position}:${img.url}`), pid,
            img.originalUrl, img.url, img.alt ?? null, img.title ?? null,
            img.caption ?? null, img.credit ?? null, img.width ?? null,
            img.height ?? null, img.mimeType ?? null, img.fileSize ?? null,
            img.role ?? null, img.position,
          ],
          "(id)",
        ),
      );
    }
    for (const f of p.faq) {
      out.push(
        insert(
          "faq",
          ["id", "page_id", "question", "answer", "position"],
          [pseudoUuid(`faq:${p.canonicalUrl}:${f.position}`), pid, f.question, f.answer, f.position],
          "(id)",
        ),
      );
    }
    for (const b of p.breadcrumbs) {
      out.push(
        insert(
          "breadcrumbs",
          ["id", "page_id", "label", "url", "position"],
          [pseudoUuid(`crumb:${p.canonicalUrl}:${b.position}`), pid, b.label, b.url ?? null, b.position],
          "(id)",
        ),
      );
    }
    for (const j of p.jsonld) {
      out.push(
        insert(
          "jsonld",
          ["id", "page_id", "type", "data", "position"],
          [pseudoUuid(`jsonld:${p.canonicalUrl}:${j.position}`), pid, j.type ?? null, j.data ?? {}, j.position],
          "(id)",
        ),
      );
    }
    for (const l of p.links.internal) {
      out.push(
        insert(
          "internal_links",
          ["id", "page_id", "href", "anchor_text", "rel", "position"],
          [pseudoUuid(`ilink:${p.canonicalUrl}:${l.position}:${l.href}`), pid, l.href, l.anchorText ?? null, l.rel ?? null, l.position],
          "(id)",
        ),
      );
    }
    for (const l of p.links.external) {
      out.push(
        insert(
          "external_links",
          ["id", "page_id", "href", "anchor_text", "rel", "domain", "position"],
          [pseudoUuid(`elink:${p.canonicalUrl}:${l.position}:${l.href}`), pid, l.href, l.anchorText ?? null, l.rel ?? null, l.domain ?? null, l.position],
          "(id)",
        ),
      );
    }
    if (p.metadata) {
      out.push(
        insert(
          "metadata",
          ["id", "page_id", "meta_tags", "http_headers", "open_graph", "twitter", "custom"],
          [
            pseudoUuid(`meta:${p.canonicalUrl}`), pid, p.metadata.metaTags ?? null,
            p.metadata.httpHeaders ?? null, p.metadata.openGraph ?? null,
            p.metadata.twitter ?? null, p.metadata.custom ?? null,
          ],
          "(page_id)",
        ),
      );
    }
  }

  out.push("", "COMMIT;", "");
  return out.join("\n");
}
